### ISSUE TITLE
Requires sudo?

### ISSUE THREAD

**Issue by markwylde** [prologic/box#1]
I'm on a linux machine and I can only get box to run with sudo access.

```bash
[mark@local box]$ ./main run alpine /bin/sh
Error: operation not permitted
```

I just wanted to confirm, this is expected right?

**Comment by prologic** [comment]
Yes this is expected because the binary needs elevated privileges to be able to actually create containers in the first place. You could also install the binary with the suid bit set.￼￼

**Comment by markwylde** [comment]
Yeah I thought as much.

very interesting about the `suid` thing. I had never realised you could do that.

It didn't work on box though :S

```
[mark@mark-librem15v4 box]$ sudo chown 0:0 ./main
[mark@mark-librem15v4 box]$ sudo chmod u+s main
[mark@mark-librem15v4 box]$ sudo chmod g+s main
[mark@mark-librem15v4 box]$ ./main ps
Error: operation not permitted
```

**Comment by prologic** [comment]
Hmmm I'll look into that... 🤔

**Comment by prologic** [comment]
Fixed.
