### ISSUE TITLE
Error: can't initialize cgroups

### ISSUE THREAD

**Issue by markwylde** [prologic/box#12]
Fresh install of linux on vultr.

**OS:** Linux vultr.guest 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
**Distro**: Debian GNU/Linux 10
**Go**: go version go1.15.5 linux/amd64

```bash
root@vultr:~/box# ./box run alpine sh
Error: can't initialize cgroups: open /sys/fs/cgroup/memory/box/3bf2d5a1d58bf8d27f668c9b300e8803c395b8855e5a7aaf2df1e842af1a22b9/memory.memsw.limit_in_bytes: permission denied
```

**Comment by markwylde** [comment]
Possibly related:
https://github.com/moby/moby/issues/10280

**Comment by prologic** [comment]
> Possibly related:
> 
> https://github.com/moby/moby/issues/10280

That linked issue is invalid argument error. May not be quite related 🤔

**Comment by prologic** [comment]
I _believe_ this error is the result of the Kernel on Debian 10 not having `CONFIG_MEMCG_SWAP_ENABLED` enabled. I should probably check for this somehow and not bother setting swap limits, since we can't.

**Comment by prologic** [comment]
Confirmed:

```#!console
root@debian-s-1vcpu-1gb-nyc1-01:~# grep CONFIG_MEMCG_SWAP_ENABLED /boot/config-4.19.0-10-cloud-amd64
# CONFIG_MEMCG_SWAP_ENABLED is not set
```

**Comment by prologic** [comment]
Okay, I _think_ these Debian 10 "cloud" images are not suitable for running containers with constrained resources:

```#!console
root@debian-s-1vcpu-1gb-nyc1-01:~# ./box version
box v0.0.6-dev@505e857
root@debian-s-1vcpu-1gb-nyc1-01:~# ./box run alpine /bin/sh
Error: can't initialize cgroups: write /sys/fs/cgroup/cpu/box/089c9cc43ff5298ebc3ee52373213b057d52ab564366844a0f4c60fe34564811/cpu.cfs_period_us: invalid argument
```

I'll fix the code to skip setting certain CG(s) that don't exists because the Kernel doesn't have that CG enabled. 👍
