### ISSUE TITLE
build fails for non-root user

### ISSUE THREAD

**Issue by misho-kr** [prologic/box#13]
The build requires superuser privilege which does not seem right. The build should not try to change the environment.

```bash
$ make 
FATA[0000] set ip forward failed: open /proc/sys/net/ipv4/ip_forward: permission denied 
make: *** [Makefile:11: dev] Error 1
```

**Comment by prologic** [comment]
That's because the default target builds && runs the binary.

Try `makee build`

Or I'll change the default target to be `all: build`?
